plugins {
    id 'com.android.application'
}

android {
    namespace 'cn.suizhang.ledger'
    compileSdk 36

    defaultConfig {
        applicationId 'cn.suizhang.ledger'
        minSdk 29
        targetSdk 34
        versionCode 19
        versionName '1.4.5'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation project(':HiMiuix')
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'com.google.mlkit:text-recognition-chinese:16.0.1'
}
